### ISSUE TITLE
History rewritten on 3-June-2018

### ISSUE THREAD

**Issue by ptressel** [elcano/elcano#165]
We found that we'd accidentally committed 3rd party (Arduino) libraries to the repository, and had also included large media files (images, videos) that don't need revision control.  These have all been stripped out.  (Many thanks to the authors of git filter-branch...)  The prior version of the repository is available temporarily at https://github.com/elcano/old_elcano.  When we're certain we have what we need out of the non-master branches there, it will be removed.

Folks with new code or changes to existing files will need to patch those in to the new repo.

**Comment by TylerFolsom** [comment]
Pat -Thanks for taking care of this.  Next step is to put current code into the new repo. How do you recommend I do so?- Tyler


-------- Original Message --------
Subject: [elcano/elcano] History rewritten on 3-June-2018 (#165)

**Comment by ptressel** [comment]
If you want to add new versions of existing files, or entire new files, then the easiest way is:  Rename your local copy of the old repo, and clone a fresh copy of elcano/elcano.  It's fine to use the master branch for this.  Copy the new / updated files that you want to go together in a single commit into the appropriate places the new clone.  Commit those as usual -- use a nice, informative commit message ;-).  Repeat for each set of files that belong together in a commit.  Once you have all the new / updated files added, then you'll need to overwrite your own TylerFolsom/elcano fork of the elcano repo (not the main elcano/elcano repo).  I just checked -- it looks like you don't have new material there, and there are no branches other than master, so it should be safe to overwrite it.  The only difference in the push command is that you'll need to add the "--force" option.  If you want me to have a look before you do this, let me know.

**Comment by ptressel** [comment]
Conor and Joe may be interested in a git fixing session, if you want to do the various git work as a group.
